[package]
name = "mock-fineco"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
httptiny = { path = "../httptiny" }

[lib]
name = "mock_fineco"
path = "src/lib.rs"

[[bin]]
name = "mock-fineco"
path = "src/main.rs"
